export const DEFAULT_UNSUB_IF_IN_BLOCK = true;
export const DEFAULT_CONTRACT_INSTANTIATION_GAS_LIMIT = 200_000_000_000;
export const DEFAULT_CONTRACT_INSTANTIATION_SALT = null;
export const DEFAULT_CONTRACT_INSTANTIATION_VALUE = 1_000_000_000_000_000;
export const DEFAULT_CONTRACT_QUERY_GAS_LIMIT = -1;
export const DEFAULT_CONTRACT_QUERY_VALUE = 0;
export const DEFAULT_CONTRACT_TX_GAS_LIMIT = -1;
export const DEFAULT_CONTRACT_TX_VALUE = 0;
